spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1

  data:
    redis:
      host: redis
      password: ${REDIS_PASSWORD}

jwt:
  public-key: ${JWT_PUBLIC_KEY}
  private-key: ${JWT_PRIVATE_KEY}