spring:
  application:
    name: notiguide

  config:
    import: optional:application-${spring.profiles.active}.yaml

  jackson:
    time-zone: UTC

server:
  forward-headers-strategy: framework

jwt:
  expiry-seconds: 86400
  private-key-password: ${JWT_PRIVATE_KEY_PASSWORD}

app:
  timezone: Asia/Ho_Chi_Minh
  cors:
    allowed-origins:
      - http://localhost:3000
