spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1

  data:
    redis:
      password: ${REDIS_PASSWORD}

jwt:
  private-key: classpath:rsa/notiguide.pem
  public-key: classpath:rsa/notiguide-pub.pem

firebase:
  credentials-path: classpath:firebase/notiguide-firebase.json

rate-limit:
  enabled: false

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001
      - http://192.168.0.7:3000
      - http://192.168.0.7:3001
      - http://192.168.204.189:3000
      - http://192.168.204.189:3001

  cookie:
    name: auth_token
    secure: false
    same-site: Strict
    domain:
    path: /api
